### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ergsfe** [walterpg/google-drive-sync#10]
I go through the google sign in process with my web browser and grant permission.  I have "limited drive access" and "targeted sync folder" selected, although I have tried toggling these options and/or changing the sync folder and the issue happens anyway.  

After granting access with the web-browser, I see the message:

"Google Drive Sync: Opening 'DriveSyncPasswords' folder..."

While this message is displayed, keepass is unresponsive.  Roughly 1 minute later, a message box appears that says "A task was cancelled."

**Comment by walterpg** [comment]
Hi,

Some more info is needed to try to track this down please.

* Which web browser and what is its version?
* Which version of KeePass?
* [What version(s) of .NET Framework are installed?](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

**Comment by ergsfe** [comment]
Keepass 2.45.  Following the guide in your link and looking at the "Release" DWORD in the registry, I have the .Net framework: "On Windows 10 May 2019 Update and Windows 10 November 2019 Update: 528040."  My default web browser, which opens when keepass attempts to connect to gdrive, is 77.0.1 (64bit).
