### ISSUE TITLE
Adding Sub-folder support in google drive.

### ISSUE THREAD

**Issue by madhav-A12341** [walterpg/google-drive-sync#16]
The keepass drive sync currently supports only top level folders. Subfolders support will be really helpful!

**Comment by walterpg** [comment]
Thank you for this enhancement request.  This is one of the outstanding issues mentioned in #14 , https://github.com/walterpg/google-drive-sync/issues/14#issuecomment-696170908

**Comment by walterpg** [comment]
Commit 04e5764 provides this functionality.
