### ISSUE TITLE
Show Username of Google Account in Drop Down List

### ISSUE THREAD

**Issue by Uranium235** [walterpg/google-drive-sync#17]
When multiple Google Accounts exist in the database selecting the right account to authorize Google Drive with is cumbersome when the entry title does not include any hint to the actual account.

I name all my Google Accounts simply "Google Account" in the title and differentiate by the login name, i.e. e-mail address.

It would be helpful - as it has been in v3 - to concatenate the entry title and username for the drop down list.

**Comment by walterpg** [comment]
Hello uran, thanks for dropping in. :wink:

Sounds like a good idea to me.  Maybe you have a PR?
