### ISSUE TITLE
Getting "Object reference not set to an instance of an object." when saving a database

### ISSUE THREAD

**Issue by atresnjo** [walterpg/google-drive-sync#18]
Basically whenever I save I get the following error
![image](https://user-images.githubusercontent.com/41112852/94333943-c7998500-ffd7-11ea-8a16-0acbae1b80e3.png)

The changes do get synchronized from what I've seen, but the error still occurs.

**Comment by walterpg** [comment]
Hi, thanks for the report, but there's not enough info to investigate the issue.  

The [Bug Report](https://github.com/walterpg/google-drive-sync/issues/new/choose) template is a guide to providing the initial basic info, some of which you have posted above.

In this case, probably the most valuable info to begin with is version information.  In particular, the KeePass version, the plugin version (from the window title in the screenshot, this appears to be 4.0.2-beta), the .NET Framework version, and Windows version.

**Comment by atresnjo** [comment]
I'm very sorry for the poor report, totally missed the template.

**Describe the bug**
MessageBox with a NullRefernceException error pops up while saving

**To Reproduce**
Steps to reproduce the behavior:
1. Add/Modify/Delete Entry
2. Press S to save changes

**Expected behavior**
No error. :)

**Screenshots**
![image](https://user-images.githubusercontent.com/41112852/94358441-51615500-00a1-11eb-9c4f-d569e0b136d7.png)

**Please complete the following information:**
 - OS: Windows 10: Version 2004 (Build 19041.508)
 - Browser: Firefox
 - Version: 4.0.2-beta
- .NET Framework version installed:
![image](https://user-images.githubusercontent.com/41112852/94358494-b452ec00-00a1-11eb-9e2f-f1768ba35587.png)

**Comment by walterpg** [comment]
Thanks, what version of KeePass are you using, and is it an "installer" or "portable" installation?

**Comment by atresnjo** [comment]
Portable installed using scoop
2.45

**Comment by walterpg** [comment]
I have tried a few things but can't reproduce this.  

Do you have any other KP plugins installed?

Do you see something like the message below in the status bar after a sync op?

![Capture](https://user-images.githubusercontent.com/15221668/95015664-bf62ca80-0613-11eb-8667-24cd5d697d5a.PNG)

**Comment by atresnjo** [comment]
Hi, sorry for the delay.

I do have other plugins installed, but the message box is from this plugin, so those shouldn't matter, or what do you think?

![image](https://user-images.githubusercontent.com/41112852/96842284-23c3bd80-144d-11eb-81a8-65ab7fb8028b.png)


This happens only when one of those options is checked:

![image](https://user-images.githubusercontent.com/41112852/96842523-6e453a00-144d-11eb-9910-f64db0597414.png)


When I sync manually, the message box does not pop up.

Yes, I do get the message below, it successfully synchronizes, but the message box pops up twice (I got two databases open)

Hope that helps, if not I'll try to dig deeper when I have time, until then I can just synchronize manually. Thanks! 👍

**Comment by feelnrg** [comment]
Hello guys,

I have the same issue. It seems that the job run into a loop.

regards

**Comment by feelnrg** [comment]
> 
> 
> Hi, sorry for the delay.
> 
> I do have other plugins installed, but the message box is from this plugin, so those shouldn't matter, or what do you think?
> 
> ![image](https://user-images.githubusercontent.com/41112852/96842284-23c3bd80-144d-11eb-81a8-65ab7fb8028b.png)
> 
> This happens only when one of those options is checked:
> 
> ![image](https://user-images.githubusercontent.com/41112852/96842523-6e453a00-144d-11eb-9910-f64db0597414.png)
> 
> When I sync manually, the message box does not pop up.
> 
> Yes, I do get the message below, it successfully synchronizes, but the message box pops up twice (I got two databases open)
> 
> Hope that helps, if not I'll try to dig deeper when I have time, until then I can just synchronize manually. Thanks! 👍

If you are using AutoExec Plugin  and you open multiple KP Files on startup by adding them into AutoOpen Folder there is a solution:  Edit the Entries in AutoOpen Folder and ad a Custom Value. Field Name: Focus  / Field Value: Restore
![grafik](https://user-images.githubusercontent.com/45741845/101226513-fd707f00-3694-11eb-89a9-ce1609aafc35.png)
