### ISSUE TITLE
Temporary files appear in Open recent

### ISSUE THREAD

**Issue by Florent4782** [walterpg/google-drive-sync#2]
![image](https://user-images.githubusercontent.com/66121810/83258328-11867180-a184-11ea-928d-4eecbd71827a.png)
No a big issue though, thank you for your work !

**Comment by walterpg** [comment]
Thanks for the report.  This is [fixed](https://github.com/walterpg/google-drive-sync/commit/97ca33c2e5be57b8c1145e73ae0aacd1b893db19) and will be in the next release.

**Comment by Florent4782** [comment]
Thank you @walterpg , looking forward to get the new release.
