### ISSUE TITLE
Stable name for plugin file - no version information in filename

### ISSUE THREAD

**Issue by Rookiestyle** [walterpg/google-drive-sync#23]
Hi!

That's not a feature request regarding the functionality of the plugin as such.
Actually I don't miss anything here, your plugin is working just fine for me - thanks for  developing and maintaining it!

I'ld appreciate if you consider using the same name for the plgx file for all releases e. g. `KeePassSyncForDrive.plgx`
This way, I would not need to delete the old plgx file during an update.
In addition, it would allow me enrich one of my plugins so that it can automatically update the newest version of your plugin as well.

Currently I'm using something like `<path to latetest release>/keepasssyncfordrive-{major}.{minor}.{build}-beta.plgx` and save it as `KeePassSyncForDrive.plgx` in my KeePass plugin folder.
Would be great if you can think of making the filename more stable - if not know, maybe once there is a stable release available without any alpha / beta suffix?

**Comment by walterpg** [comment]
The "beta" suffix will go away, hopefully soon.  Will that be sufficient for your purposes?  I know there is a possibility for duplication/confusion but I think most people can understand what is going on much more clearly if the .plgx files have a distinct version number.

**Comment by Rookiestyle** [comment]
I'm happy to read that beta phase might be completed soon, this will already help a lot.
This way the filename will be stable in a sense of variable parts (version number) are known and can be merged in for the download.

I agree that plgx files having a distinct version number makes it easier to tell which version of the plugin is in use.
On the other side, this is only neccessary if the plugin cannot be loaded. 
KeePass shows the plugin version as well and I **guess** most users will first have a look there before checking filenames in the plugins folder

I'll find a way to either automatically delete `KeePassSyncForDrive-4.0.4.plgx` when `KeePassSyncForDrive-4.0.5.plgx` is available or to simply save it as `KeePassSyncForDrive.plgx`

**Comment by walterpg** [comment]
There will be at least one more beta release.  I see that you made some changes to your plugin, but I'm not sure if they involve this issue.  

You can count on the prefix of the file name (disregarding the .zip/.plgx extensions) to always be "KeePassSyncForDrive-". The remainder of the string follows the [SemVer](https://semver.org/) spec.  SemVer doesn't address encoding file names,
but most "package" files I've seen seem to follow this pattern, with some variations in the separator at the end of the package name (mypkg+1.3.4.pkg, etc.).  

You might look into using a SemVer RegEx or a compatible parser project.  A quick search showed at least two .NET/nuget SemVer libraries here on Github.

**Comment by Rookiestyle** [comment]
Thanks for your feedback.
I can work with that just fine.

Only remaining issue: KeePass' update check does not tell whether the new relesae is a beta release or not and due to that, automatic update will fail once your plugin will leave beta phase.
That's a one time issue only
