### ISSUE TITLE
Impossible to connect

### ISSUE THREAD

**Issue by GatitoStudio** [walterpg/google-drive-sync#24]
Hello 

i can't synchronise my google account : 
![image](https://user-images.githubusercontent.com/14920191/101488238-a4883b80-395f-11eb-9b6b-192be526df84.png)

Please, help me :/

**Comment by rootless4real** [comment]
Try using the new authentication method available now.  That makes a huge
difference.

The old method will often result in the error you are receiving.  Google is
trying to stop that way.
