### ISSUE TITLE
KP2 Error: A newer .NET framework is required

### ISSUE THREAD

**Issue by leder11011** [walterpg/google-drive-sync#26]
**Describe the bug**
I have installed both:
- keepass2 v2.45 under ubuntu 20.04 from repository ppa:jtaylor/keepass
- .NET v5.0.101
- beta plugin from this site

**To Reproduce**
1. Go to '/usr/lib/keepass2/Plugins'
2. sudo cp 'KeePassSyncForDrive-4.0.3-beta.plgx' .
3. Start keepass2
4. See error from screenshot

**Expected behavior**
I want to use the packaged keepass2 b/c I had no luck installing the mono version by myself. Additionally I want to be able to install the plugin from this repository.

**Screenshots**
[keepass2_error](https://paste.pics/752b34eee57848319f14843ada2731cc)

**Please complete the following information:**
 - OS: ubuntu 20.04
 

**Additional context**
n/a

**Comment by walterpg** [comment]
Currently, this repo's releases [officially](https://www.kpsync.org/install/require) only support Windows and .NET 4.5 or later (not mono, etc.).  

If anyone manages to modify the plugin to work on other platforms, please let us know!

**Comment by leder11011** [comment]
as described in OP I have installed .net 5: the test for .net version in the plugin seems not to be the solution, but the problem! is it possible for you to provide a developer version of your plugin w/o that version test?

**Comment by walterpg** [comment]
To clarify:

* The package you are using ([ppa:jtaylor/keepass](https://launchpad.net/~jtaylor/+archive/ubuntu/keepass)) claims to support Mono, not .NET 5 or .NET Framework. The plugin, by definition, can only use the .NET platform that its KeePass host program is running under.
* This plugin currently supports **.NET Framework** releases higher than 4.5. The latest, final version of .NET Framework is [4.8](https://docs.microsoft.com/en-us/dotnet/framework/install/).
* .NET 5 is *not* a .NET Framework release. Though much of the API is compatible, Microsoft's current position is that .NET 5 will only ever support "forms" applications, such as KeePass and the plugin, which run on Windows exclusively.
* The error dialog shown in your screenshot is not produced by the plugin, it is produced by KeePass.  It is KeePass, not the plugin, that performs the "test" you mention.  For example, you will see the same message when running KeePass on Windows with .NET Framework 4.0.

At this time, the project lacks resources to officially support alternative .NET platforms like Mono.  Coordination with contributors willing to undertake such an effort could be possible.  However, please note that the Google API package upon which the plugin currently depends [does not support Mono](https://www.nuget.org/packages/Google.Apis.Drive.v3).  

[Everyone has full access to the code](https://github.com/walterpg/google-drive-sync): this is the "developer version" you speak of. The maintainers of the project track KeePass development with interest; [if there is a .NET5/6 compatible release in the future](https://sourceforge.net/p/keepass/discussion/329220/thread/3126092352/), a fork to develop support for it is very likely.

In the meantime, [KeePass documentation offers guidance](https://keepass.info/help/v2/setup.html#wine) for running KeePass supporting .NET Framework 4.5 under Wine.  Though neither this project nor the Google Drive API offer support for that scenario, it could be the path of least resistance for you.

**Comment by leder11011** [comment]
Hello Walterpg,
what you are writing may be right: But installation of wine howto failed silently, I filed a bug with Dominik. Then there is the issue with the platform agnostic version of `keepass2` for .NET 5.0 and the mono version giving an error about .NET versions, cp. OP:
Don't you wanna do something? Falling back on the excuse of having no time and closing this issue is very weak!

Best regards
leder11011

**Comment by dregad** [comment]
This affects me as well.

@walterpg thanks for the detailed explanation, and hopefully the KeePass teem will eventually migrate to .NET 5.

For the record, I have tried hard but never could get KeePass to run on Wine. jtaylor's PPA is the only thing that works for me on Ubuntu. Sadly, this means manual sync of the kbdx file though...

**Comment by leder11011** [comment]
Yes, Damien: I totally agree! Got keepass2 running from the PPA with the
additional effort of file sync with syncthing. This has the advantage of
keeping Google out! Thanks again @walterpg for your explanation. And again
a vote up for .NET 5.

Damien Regad <notifications@github.com> schrieb am Mo., 22. Feb. 2021,
19:19:

**Comment by dregad** [comment]
> hopefully the KeePass teem will eventually migrate to .NET 5

Don't hold your breath...
https://sourceforge.net/p/keepass/discussion/329220/thread/3126092352/#1c78
