### ISSUE TITLE
Bug Report - Not working on 2.47 

### ISSUE THREAD

**Issue by isipka** [walterpg/google-drive-sync#27]
**Describe the bug**
Not working on Keepass 2.47 portable gives a compatibility worning on starting Keepass. 4.0.3beta is unzipped in Plugins subfolder of Keepass portable folder

**Comment by walterpg** [comment]
I'm sorry it's not working for you.  If you are still having problems after verifying that your environment meets the [requirements](https://www.kpsync.org/install/require), please respond with details of the warning and your:
* Windows version
* [.NET Framework version](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)


I just verified that the current release (4.03-beta) works without warnings on [KeePass 2.47](https://keepass.info/news/n210109_2.47.html) in the following environment:
* Windows 10, v.2004
* .NET Framework 4.8

**Comment by isipka** [comment]
![image](https://user-images.githubusercontent.com/6573304/105197806-4beeb580-5b3d-11eb-8c5b-5d6abcc15d84.png)

**Comment by isipka** [comment]
![image](https://user-images.githubusercontent.com/6573304/105197939-704a9200-5b3d-11eb-98b5-eb5d1ed53d10.png)

**Comment by isipka** [comment]
.NET version =  4.8.04084

**Comment by walterpg** [comment]
Try clearing the plugin cache? (In KeePass, menu Tools | Plugins... → click Clear button, restart)

Also make sure there aren't any extra copies of KeePassSyncForDrive.dll (or the old name, GoogleDriveSync.dll) anywhere else in the KeePass or KeePass\Plugins folders.  For that matter, remove _any_ duplicates of plugin assemblies.

If you still have trouble, try running with the `debug` command-line parameter to see if there's any more info available, e.g.

`KeePass.exe "C:\My Documents\MyDatabase.kdbx" -debug`

**Comment by walterpg** [comment]
I just verified the zipped plugin package on a "clean" KP 2.47 portable runs with no problems.  Something is interfering with the Fusion loader in your case.  KeePass installations include an app config file (`KeePass.exe.config`) which *must* be in the same folder as `KeePass.exe`.  For 2.47 it should look like this:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<startup useLegacyV2RuntimeActivationPolicy="true">
		<supportedRuntime version="v4.0" />
		<supportedRuntime version="v2.0.50727" />
	</startup>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="KeePass"
					publicKeyToken="fed2ed7716aecf5c"
					culture="neutral" />
				<bindingRedirect oldVersion="2.0.9.0-2.47.0.0"
					newVersion="2.47.0.21109" />
			</dependentAssembly>
		</assemblyBinding>
		<enforceFIPSPolicy enabled="false" />
		<loadFromRemoteSources enabled="true" />
	</runtime>
	<appSettings>
		<add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
	</appSettings>
</configuration>
```

The important parts for plugins are `<assemblyIdentity>` and `<bindingRedirect>`.  `publicKeyToken` and `newVersion` attributes must match the assembly attributes of `KeePass.exe`.  Each KP release will include an updated version of `KeePass.exe.config` to reflect the release version.

For example, I can replicate the OP behavior when I change "fed2ed7716aecf5c" to "ged2ed7716aecf5c" in the above file.

Note also that the application config file can be overridden by the `machine.config` file for the .NET framework.  So if you happened to have edited that file to modify the above binding, that could be an issue.

**Comment by nob0dy80** [comment]
Not working for me too.
Fresh portable keepass 2.47 portable + .Net 4.8
When hitting "configure" i got this:

`
************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei KeePassSyncForDrive.PluginEntryFactory.Create(String title, String driveScope, String clientId, ProtectedString clientSecret, String folder, Boolean useLegacyCreds, Boolean dontSaveAuthToken) in C:\src\kp\master\walterpg1v-kp-googlesync\src\PluginEntryFactory.cs:Zeile 65.
   bei KeePassSyncForDrive.PluginEntryFactory.CreateDefault(String title) in C:\src\kp\master\walterpg1v-kp-googlesync\src\PluginEntryFactory.cs:Zeile 39.
   bei KeePassSyncForDrive.KeePassSyncForDriveExt.GetEntryFactory() in C:\src\kp\master\walterpg1v-kp-googlesync\src\GoogleDriveSyncExt.cs:Zeile 1684.
   bei KeePassSyncForDrive.KeePassSyncForDriveExt.AskForConfiguration() in C:\src\kp\master\walterpg1v-kp-googlesync\src\GoogleDriveSyncExt.cs:Zeile 1600.
   bei KeePassSyncForDrive.KeePassSyncForDriveExt.OnConfigure(Object sender, EventArgs e) in C:\src\kp\master\walterpg1v-kp-googlesync\src\GoogleDriveSyncExt.cs:Zeile 341.
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4300.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------`

**Comment by walterpg** [comment]
Thanks for pasting the call stack, but the plugin version information is vital if we are to follow up on this.  If it doesn't show in the KP "plugins" page, look at the properties of the KeePassSyncForDrive.dll file for the "File Version".

**Comment by wolfcreative** [comment]
I have the same problem. Only version 4.0.3 works correctly.

**Comment by walterpg** [comment]
Please try updating to the [current release](https://github.com/walterpg/google-drive-sync/releases/tag/v4.0.7-beta) and let us know how it goes.

**Comment by wolfcreative** [comment]
@walterpg The new version works great. Thank you!
