### ISSUE TITLE
Bug Report - 4.0.4beta

### ISSUE THREAD

**Issue by tim1014** [walterpg/google-drive-sync#29]
**Describe the bug**
Version 4.0.4beta is not working on KeePass 2.47. I've already cleaned up the plugin cache folder and still getting the warning message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clean up the old plugin and plugin cache files.
2. Copy the latest plugin into "Plugins" folder
3. Start KeePass

**Screenshots**
![01](https://user-images.githubusercontent.com/19739878/106425193-7d04a980-649e-11eb-9d01-f277872418f6.png)

System Info:
 - OS: Windows 10 Version 2004
 - .NET Framework 4.8.04084
 - KeePass v2.47
 
 Is anyone get the same problem?

**Comment by bgatellier** [comment]
Hi,

Same error here, and I tried to the clear the plugin the plugin cache and reboot too.

System Info:
    OS: Windows 10 Family Version 20H2 (19042.746)
    KeePass v2.47

For now, I'm rolling the plugin back to the 4.0.3 version.

Thanks for the plugin anyway 😃

**Comment by rom-1** [comment]
Jepp, same here, German Windows 10 OS 20H2,

**Comment by fourofspades** [comment]
Broken for me also.  Think this might be a pretty widespread problem.

**Comment by whalehub** [comment]
> Is anyone get the same problem?

Yeah, I just experienced this issue as well after upgrading from 4.0.3 to 4.0.4.

**Comment by ImFilippo** [comment]
Same error here.
Keepass 2.47

**Comment by walterpg** [comment]
Apologies, I can confirm this is a bug in 4.0.4-beta (thanks to @Rookiestyle). I will pull this release from the web site.  The fix is in work as PR #30.
