### ISSUE TITLE
Rename the plugin in compliance with KeePass naming suggestions

### ISSUE THREAD

**Issue by dregad** [walterpg/google-drive-sync#31]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a link to https://www.kpsync.org/ on the official KeePass web site's Plugins page https://keepass.info/plugins.html

**Describe alternatives you've considered**
Use the plugin's _about_dialog, bookmark the site or use Google; it's all fine 😃  

**Additional context**
This is only for convenience to users, since when KeePass detects a new version of the plugin, it links to that page

Many thanks for your efforts to maintain and improve this very useful plugin, it is much appreciated !

**Comment by walterpg** [comment]
Hi, thank you for you kind words.

The addition of a link to the latest release from the plugin is possible and a good idea.

We have no control over the KeePass website.  Also, since the plugin's current branding is in conflict with KeePass' stated preference for plugin names (found at the very bottom of the keepass.info page you linked), I doubt they will be receptive to requests from me.  

But please, feel free to make you own request to keepass.info!

**Comment by dregad** [comment]
> since the plugin's current branding is in conflict with KeePass' stated preference for plugin names

In that case it may be a good idea to rename the plugin to avoid abuse of the KeePass brand name :wink:

**Comment by walterpg** [comment]
> In that case it may be a good idea to rename the plugin

Excellent idea.  Actually this is another reason this is still beta software.

(Yet another) name change will require Google's re-verification of the software.  It appears that the process *could* take place without effecting the functionality of existing OAuth grants, which was a primary concern.  So I suppose we can hold our breath and give it a try.

### Now, what do you suppose we should call it?
Please share your thoughts and keep in mind the domain name of the documentation website is kpsync.org, which will *not* be changed.

Also, the suffix "for Google Drive™" must remain as-is, for Google's naming regulations.

**Comment by Rookiestyle** [comment]
Not being the most creative guy:
* KPSync for Google Drive™
* KeePassSync for Google Drive™

I'ld volunteer to test a pre-release (existing OAuth grants) if it helps.

**Comment by dregad** [comment]
> the domain name of the documentation website is kpsync.org, which will not be changed.
> Also, the suffix "for Google Drive™" must remain as-is

Given these constraints, _KPSync for Google Drive™_ seems the more logical choice. But I'm also not a creative guy :wink:

**Comment by walterpg** [comment]
Implemented in v4.0.6-beta.

**Comment by dregad** [comment]
Just installed the new version, thanks.

Also noticed that it is now [referenced on KeePass plugins page](https://keepass.info/plugins.html#kpgsync)
![image](https://user-images.githubusercontent.com/449891/112842834-4021f100-90a2-11eb-84f1-2c2b47d1ca5d.png)
