### ISSUE TITLE
Error with plugin when saving a Database and Auto-Sync is on.

### ISSUE THREAD

**Issue by pmorange** [walterpg/google-drive-sync#32]
**Describe the bug**
In the plugin settings I hace selected the Auto-Sync "Sync when Saving a KeePass Database"
When I save the database (Either via Ctrl-S or the save icon), I receive an error  from the plugin : "URI formats are not supported"
If just afterwards I click on "Sync with Drive", no error is displayed and all works well.

**To Reproduce**
 - Select Auto-Sync "Sync when Saving a KeePass Database" option in the plugin configuration.
 - Save the database.

**Expected behavior**
The database is saved and synced to Google Drive.

**Screenshots**
<img width="150" alt="2021-02-23 16_22_36-Search" src="https://user-images.githubusercontent.com/8950440/108865921-0027a400-75f4-11eb-994a-64224a5c4d40.png">

**Please complete the following information:**
 - OS: Windows 10 Version 10.0.17763 Build 17763
 - KeePass v2.47 64 bits
 - Plugin Version 4.0.5-beta

Thanks

**Comment by walterpg** [comment]
Hi,

Could you provide a few more details please?  In particular:

What other plugins have you installed?

Do you use any other sync utility, such as KP's "Synchronize with...", or a different plugin's sync feature?

The plugin's sync command relies on KP to provide the database file path info when the op begins.  From the perspective of the plugin, there is no difference between invoking the sync op via the plugin menu command or from the KP "save file" event, the latter to which the auto-save feature is hooked.  I suspect that something, such as another plugin, is causing the database file location to change when you save the file.

**Comment by pmorange** [comment]
Hi,

Indeed, I have another plugin : KPSimpleBackup.
I had activated the option to automatically save a backup of the DB when saving the main DB, and that seems to have been the cause of the problem. I changed it to make a backup when closing the DB and/or application, and deactivated it when saving the DB.
The problem has now disappeared, many thanks for pointing me in the right direction.

Regards,
Philippe.

**Comment by walterpg** [comment]
After giving this some thought, there probably is a bug in the plugin here.

The sync ops run asynchronously. Thus KP's "current" database may have changed by the time the Google download is complete, since the KP main thread moved on to service your other plugin attached to the save event.

There may need to be some restructuring of the event handler to create a context for the sync op in this case.

**Comment by walterpg** [comment]
Possibly linked to issue #18 (similar auto-sync condition).
