### ISSUE TITLE
When database goes into auto-lock. Error: Empty path name is not legal. 

### ISSUE THREAD

**Issue by luuk89** [walterpg/google-drive-sync#36]
**Describe the bug**
When I add a new entry/make a change and I switch screens and let the database go into auto-lock. I get an error: "Empty path name is not legal."
Database does not get synced before it goes in to auto-lock. I have had this for a while, but never bothered to make a report. Currently using latest plugin 4.0.6

**To Reproduce**
1. Create new entry.
2. Let database go in to auto-lock.
3. Small window with error appears, see screenshot.

**Expected behavior**
Sync database before it goes into auto-lock

**Screenshots**
https://imgbox.com/6mDBmfi6

**Please complete the following information:**
 - OS: Windows 10 x64 version 20H2 build 19042.867
 - Browser N/A
 - Version 4.0.6-beta

**Additional context**
N/A

**Comment by Gnarfoz** [comment]
This has always felt like a race-condition to me...

**Comment by walterpg** [comment]
Could you please elaborate on this phrase: "I switch screens and let the database go into auto-lock"?  Specifically, what is "auto-lock", how is it engaged, etc.?

**Comment by walterpg** [comment]
If "auto-lock" is related to the plugin's [auto sync](https://www.kpsync.org/usage/autosync) features, it may have been addressed in the [fixes](https://github.com/walterpg/google-drive-sync/commit/418243293c85626adcb526cf324726db555b680d) for #32 & #18, which will be in the next release.

**Comment by luuk89** [comment]
> 
> 
> Could you please elaborate on this phrase: "I switch screens and let the database go into auto-lock"? Specifically, what is "auto-lock", how is it engaged, etc.?

![autolock](https://user-images.githubusercontent.com/76914094/115988082-5abf8b00-a5b8-11eb-9f63-0929eaaad6a3.PNG)

With auto-lock I mean when the database locks itself after a set amount time of inactivity. So this happens when you create a new entry, don't save, let the database lock itself because of inactivity. Then you get this error.

**Comment by walterpg** [comment]
Thank you!  

We need some more research on KP's auto-lock feature, but it appears that the plugin's auto-sync feature is invoked during KP's auto-lock sequence.  This is a problem, because plugin ops are "asynchronous" activities.  For example, if the sync op required you to enter your Google credentials, you might not be able to because of a locked screen, etc.

For now, you can think of the (otherwise incoherent) error message as a warning that you probably need to sync your database after you unlock from auto-lock.

**Comment by walterpg** [comment]
It appears this issue extends to all KP features involving composite operations which automatically save changes then close the database (the KP CloseDocument function).  For example, you can close KP with unsaved changes and "auto-save" enabled, and the plugin's Auto Sync will fail (silently), for obvious reasons.

It should be possible for the plugin to detect these sequences, and mark the database as "needs sync" (if Auto Sync is enabled) before it is saved/closed.  Then when the database is reopened, users could be prompted to invoke the "deferred sync", etc.   Thoughts?

**Comment by walterpg** [comment]
After more research, it appears the plugin has to punt on this.  As mentioned in the prior post, the unsafe "auto sync after save" condition can be detected (and the database marked as "Needs Sync"), but the condition cannot be remediated, at that moment, without breaking this somewhat specious KP security feature.  

The only reliable remedy is to offer an optional "deferred" sync when a database that has been closed by auto-lock, or save-on-exit, is reopened. The latter case could possibly be handled by the plugin, but for now, it will be treated the same.  That is, when a database is (re)opened, the plugin will heed its Needs Sync status, and ask if you wish to perform the deferred sync.  An option will also be available to automatically sync a Needs Sync database without intervention.

This fix will be in the next release.  For now, one workaround is to enable the "Sync on Open" option and ignore the error message.  Note however that Sync on Open applies to all database opens, not only this case, so you may redundantly (or inadvertently) sync the database in other cases.
