### ISSUE TITLE
Error attempting to open configuration settings

### ISSUE THREAD

**Issue by BenJ-Wisco** [walterpg/google-drive-sync#37]
I previously used the Google Sync Plugin.  Added this plugin because of a change to Google Authentication.
After installation, I first wanted to configure the plugin but receive a null reference exception error every time I attempt to.

**To Reproduce**
1. Install Plugin in \Plugins\KPSyncForDrive
2. Open existing KeePass2 db
3. Click on Tools -> KP Sync for Google Drive -> Configure

**Expected behavior**
Should open the configuration window as described on [this KP Sync page.](https://www.kpsync.org/install/config)

**Screenshots**
![001](https://user-images.githubusercontent.com/45764124/115869271-44240300-a403-11eb-9961-b76681a044bc.png)
![002](https://user-images.githubusercontent.com/45764124/115869431-7df50980-a403-11eb-97bb-7e5e94d0b9f9.png)

**Please complete the following information:**
 - OS: Windows 10 1909 Build 18363.1500
 - KeePass2 2.47 (Portable)
 - KPSync for Google Drive 4.0.6
 - Other Plugins Installed
 - KeeAgent 0.12.1

**Additional context**
Text from error

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

Exception Text
System.NullReferenceException: Object reference not set to an instance of an object.
   at KPSyncForDrive.EntryConfiguration..ctor(PwEntry entry)
   at KPSyncForDrive.KPSyncForDriveExt.AskForConfiguration()
   at KPSyncForDrive.KPSyncForDriveExt.OnConfigure(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

KeePass
    Assembly Version: 2.47.0.21109
    Win32 Version: 2.47.0.0
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/KeePass.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

KPSyncForDrive
    Assembly Version: 4.0.6.0
    Win32 Version: 4.0.6.0
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/Plugins/KPSyncForDrive/KPSyncForDrive.dll

Google.Apis.Drive.v3
    Assembly Version: 1.49.0.2030
    Win32 Version: 1.49.0.2030
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/Plugins/KPSyncForDrive/Google.Apis.Drive.v3.DLL

System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll

Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/Plugins/KPSyncForDrive/Newtonsoft.Json.DLL

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

KeeAgent
    Assembly Version: 0.12.1.0
    Win32 Version: 0.12.1.0
    CodeBase: file:///C:/Users/ben/AppData/Local/KeePass/PluginCache/CymArOTqTPisY3rBOI4i/KeeAgent.dll

SshAgentLib
    Assembly Version: 0.9.4.0
    Win32 Version: 0.9.4.0
    CodeBase: file:///C:/Users/ben/AppData/Local/KeePass/PluginCache/CymArOTqTPisY3rBOI4i/SshAgentLib.DLL

SshAgentLib.WinForms
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Users/ben/AppData/Local/KeePass/PluginCache/CymArOTqTPisY3rBOI4i/SshAgentLib.WinForms.DLL

KeePass.XmlSerializers
    Assembly Version: 2.47.0.21109
    Win32 Version: 2.47.0.21109
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/KeePass.XmlSerializers.DLL

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Google.Apis
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/Plugins/KPSyncForDrive/Google.Apis.DLL

Google.Apis.Core
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/Plugins/KPSyncForDrive/Google.Apis.Core.DLL

Google.Apis.Auth
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Storage/Ben/KeePass2/Portable/Plugins/KPSyncForDrive/Google.Apis.Auth.DLL

System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by walterpg** [comment]
Thanks for this report. The details  should lead to swift resolution.

**Comment by ZardoZAntony** [comment]
Win 7 64bit Pro, i have this error too.

**Comment by thehinglishgamer** [comment]
Same issue on Windows 10. Keypass Portable (Latest) + Plugin version 4.0.6 beta (for portable)

**Comment by walterpg** [comment]
Thanks for the recent reports.  Please remember to also fully post your complete environment, especially OS, .NET, KP, and plugin versions, and portable vs. normal install.

Can we say this effects only portable installations, or does anyone with a non-portable install have this issue as well?

Can a new (empty) database be created that exhibits the behavior?

**Comment by thehinglishgamer** [comment]
> Thanks for the recent reports. Please remember to also fully post your complete environment, especially OS, .NET, KP, and plugin versions, and portable vs. normal install.
> 
> Can we say this effects only portable installations, or does anyone with a non-portable install have this issue as well?
> 
> Can a new (empty) database be created that exhibits the behavior?

I haven't used this plugin previously. First time install. 
OS - Win 10 64bit - 20H2
.NET - 4.8.4084.0
KP - 2.47 portable
Plugin version - Compiled 4.0.6

**Comment by walterpg** [comment]
Please reopen if the [new release](https://github.com/walterpg/google-drive-sync/releases/tag/v4.0.7-beta) does not resolve this.

**Comment by BenJ-Wisco** [comment]
Sorry it took a while for me to try this again.  After copying the file referenced in #41, I tried this operation again.  Still having an issue when attempting to configure the plugin.

* KeePass2 2.48.1 (Portable)
* KPSync 4.0.7
* KeeAgent 0.12.1

Do you need all the detail from the "Unhandled Exception" error again?

**Comment by walterpg** [comment]
Hi, #41 refers to a plugin loading problem, while the exception you originally posted is being raised in the loaded plugin.

Please post the current exception's "Text from error" as you did in the original post.

**Comment by walterpg** [comment]
@BenJ-Wisco, I'm closing this for now as there has been no response for a while.  If you are still having problems, please post the information requested above in a new issue.
