### ISSUE TITLE
setup issue - can't sign in 

### ISSUE THREAD

**Issue by yaron86** [walterpg/google-drive-sync#38]
i have installed the KPGoogleSync and setup what needed (hope so) in the google developer console
i have enterned the client id and the secret key. when i try to save the db, it show me this image:
https://prnt.sc/11zvbr4
which says: "keepass this browser or app may not be secure"

how this can be fixed?

**Comment by walterpg** [comment]
Here is the image linked in the prior post:
![download](https://user-images.githubusercontent.com/15221668/115976384-2a81d900-a533-11eb-92dd-58f05fd78a09.png)

The project offered here is based on [Google Sync Plugin](https://sourceforge.net/projects/kp-googlesync/), but that package is no longer supported here or elsewhere.

Please consider uninstalling Google Sync Plugin, then downloading and installing the [current plugin](https://www.kpsync.org/).

**Comment by yaron86** [comment]
ok i just installed the new version and i am trying to start over with the google console developer
on this section here under OAuth consent screen:
![image](https://user-images.githubusercontent.com/3582979/115981620-b597b900-a59d-11eb-8ada-86527df86eae.png)
there is a section called "App domain" what should i fill there? and also what should i fill under "Authorized domains"?
