### ISSUE TITLE
DB - Failed to save to the specified file! Access is denied

### ISSUE THREAD

**Issue by endlessracingz** [walterpg/google-drive-sync#39]
I am using this plugin with two different PCs and only one of them is receiving this error when the sync is performed with my KeePass DB in Google Drive. The local copy of the DB is saved in my users Documents folder on both PCs I did however move the Windows 10 Documents folder for my user to another drive partition: D.

When a sync occurs this message appears and a *.tmp version of my DB appears.

![image](https://user-images.githubusercontent.com/6493594/116825442-41808680-ab44-11eb-902b-2d12f9597df7.png)

I then sync my other PC and the changes appear to have synced correctly. I am not entirely sure what is going on.

I was able to save a copy of my DB on the PC with the issue to my desktop and it synced without this error. It may be that this error is specific to the certain directories.

**Comment by walterpg** [comment]
Can you explain further this statement please?

>When a sync occurs this message appears and a *.tmp version of my DB appears.

Where does the "*.tmp version" DB appear?

At any rate, this is a KeePass dialog, not associated with the plugin.  It appears that KP is having trouble saving your file in the redacted location.  Maybe check user permissions on that path.

**Comment by endlessracingz** [comment]
The *.tmp version was saving in the same directory as my database. I am not sure why it is having trouble saving my file especially since the *.tmp file is being created in the same directory.

The footer in keepass is showing that the DB "has successfully been synchronized and uploaded" at the same time.

Are you aware of any there logs for this plugin or keepass? I wasn't able to find any browsing the installation directory. So far it only appears to be an inconvenience as it does appear to be syncing and saving locally.

**Comment by walterpg** [comment]
The plugin creates temporary files (downloaded from Drive) in the "temp" directory, as [configured for the system](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-5.0&tabs=windows#remarks).

The next plugin release will have a minimal logging facility, though I doubt it will help much with your issue.

For now, my advice is to troubleshoot your Windows temp directory and KeePass settings.

**Comment by walterpg** [comment]
While there is a [crude logging facility](https://github.com/walterpg/google-drive-sync/releases/tag/v4.0.7-beta) in the current release, a more accessible interface will be available in the next release.  I'm closing some old issues with unanswered questions.  If you still are having problems, please open a new issue.
