### ISSUE TITLE
4.0.7-beta identifies itself as 4.0.6-beta

### ISSUE THREAD

**Issue by meyomey** [walterpg/google-drive-sync#43]
Hi i have the same problem. How can it be solved?
Thanks, meyomey

_Originally posted by @meyomey in https://github.com/walterpg/google-drive-sync/issues/40#issuecomment-841392600_

**Comment by Rookiestyle** [comment]
In my case (#40) it helped to delete the plugin cache
`Tools -> Plugins... -> Clear`

If this does not help, I have no other idea unfortunately

**Comment by meyomey** [comment]
Yes that was the right hint! It shows now the correct version.
Thank you!
@walterpg: i think this should be added to the Installation/Upgrade section

**Comment by diver864** [comment]
it helped to delete the plugin cache
> `Tools -> Plugins... -> Clear`
Just another data point, works for me too, with KP 2.48.1 on W10, 64-bit

**Comment by wenz** [comment]
Same here! FWIW that was the first version where this was necessary.

**Comment by walterpg** [comment]
This is a problem with the current release's .PLGX archive.  As suggested, some docs were added to the installation page to provide some guidance in such matters, and the current release notes were updated.

Sorry for the inconvenience.  This will be fixed in the next release.
