### ISSUE TITLE
Google account login error

### ISSUE THREAD

**Issue by AbsPlayer** [walterpg/google-drive-sync#5]
Hi!
When I start KeePass with GoogleDriveSync-4.0.1-alpha.2 installed plugin, the system redirects to the google page.
Message is
Google sign-in is temporarily disabled for this application
This app has not yet been verified for Google Sign-in.
Error screen - https://photos.app.goo.gl/nNaEM89NNoAFCK3u5

**Comment by walterpg** [comment]
Hello, thank you for trying the plugin.

This is a [known issue](https://github.com/walterpg/google-drive-sync/issues/3#issuecomment-637851334) with the built-in OAuth credentials.  It is at the top of the task list.  In the meantime, there are working alternatives that are [lightly documented](https://github.com/walterpg/google-drive-sync/blob/master/doc#configuration).  If you want to try these, I recommend using a new "test" database to ensure they will work for you as expected before syncing your "real" database.

First, the "limited Drive access" option will reduce the access scope of the plugin, and will allow you to sync using the built-in credentials, with some caveats mentioned in the docs:
![limited](https://user-images.githubusercontent.com/15221668/83947816-fdbfb880-a7de-11ea-962e-da03ca2926ea.PNG)

Traditionally many users have obtained their own OAuth app credentials, which can be added to the database. This is also mentioned in the [docs](https://github.com/walterpg/google-drive-sync/tree/master/doc#obtaining-custom-oauth-20-credentials). This should work with either the limited or unlimited options.  But beware, if you use Chrome, the first time you authenticate this way you might be "warned" that it could be "unsafe", though it is completely secure.
![unlimited](https://user-images.githubusercontent.com/15221668/83948019-3d3ad480-a7e0-11ea-9d5a-bd9b6c8c71e6.PNG)

The intention is to fix the built-in credentials issue prior to beta releases.

**Comment by AbsPlayer** [comment]
Thank you for replying!
Your advice to use limited Drive access worked.
Once more time - many thnx
