### ISSUE TITLE
Error 400 when save or open with google sync

### ISSUE THREAD

**Issue by juno62** [walterpg/google-drive-sync#77]
**Describe the bug**
I get an error 400, Invalid Request Error when ever I have google sync plugin installed. and when ever I try to save or sync to Google drive 
Error 400 says "You can't sign into this app because it doesn't comply with the Oauth 2.0 Policy for keeping apps secure. You can let the app developer know that this app doesn't comply with one or more Google validation rule."
 
I used to just open the password safe form google drive and never had a problem till recently. I changed google accounts and I noticed there was an update in to Keepass last month. Not sure if one or the other had any thing to do with my issue. 

**To Reproduce**
1. Go to Tools
2. Click on "Google Sync Plugin"
3. Scroll down to 'synchronize with Google Drive'
4. See error. The error locks up Keepass and I have to exit the application.
5. The error will also be received if I open from Google Drive directly

**Expected behavior**
Application syncs with Google drive

**Screenshots**
![Google sync Error 400](https://github.com/walterpg/google-drive-sync/assets/53403716/da48ce98-d408-43cc-bc90-04e7d1dc7c0b)
![Google Sinc Config](https://github.com/walterpg/google-drive-sync/assets/53403716/032d0ec0-c754-45e9-b1da-f4bc2662d30a)
![Key Pass Google Entry](https://github.com/walterpg/google-drive-sync/assets/53403716/a18995a9-ad40-4b5c-9f0c-48e5f1927f4a)

**Please provide the following information:**
 - Windows 10 build 19045
 - Firefox  
 - Plugin Version 3.01
 - KeePass Version 2.55
 - "Normal" KP installation?
 - None

**Additional context**

**Comment by walterpg** [comment]
I highly recommend upgrading from your 3.01 plugin version, which uses the prior maintainer's now-invalid app ID to the current release, available [here](https://www.kpsync.org/), which uses an approved app ID.  Try that and report any issues here.
