### ISSUE TITLE
Google started blocking KPSync

### ISSUE THREAD

**Issue by alexeylef** [walterpg/google-drive-sync#81]
**Describe the bug**
Google recently (last couple of weeks) started blocking KPSync with "Google hasn't verified this app" (see screenshot). 

**To Reproduce**
1. Attempt to sync
2. Login to Google account in the browser
3. See error

**Expected behavior**
Sync should succeed

**Screenshots**
![KPSync Error](https://github.com/user-attachments/assets/67dc5fc6-ca34-43dc-b9f2-90fb8770c937)

**Please provide the following information:**
 - OS, including version and build numbers: Windows 10 Pro, Build 19045
 - Browser and version: Firefox 128.0.3
 - Plugin Version: 4.1
 - KeePass Version: 2.57

 - "Portable" or "Normal" KP installation? Normal
 - List all other plugins in use, and their version: KeePassRPC 2.0.2

**Additional context**
For some reason, on my son's computer Google gives a different message that this app is blocked and does not even show the Advanced link. He is using Chrome, maybe it has something to do with the difference.

**Comment by liteCarma** [comment]
@alexeylef  https://github.com/walterpg/google-drive-sync/issues/79#issuecomment-2275199540

**Comment by alexeylef** [comment]
> @alexeylef [#79 (comment)](https://github.com/walterpg/google-drive-sync/issues/79#issuecomment-2275199540)

Thanks, not sure how I missed that issue

**Comment by alexeylef** [comment]
Duplicate of https://github.com/walterpg/google-drive-sync/issues/79
